language: java
install: mvn install
addons:
  ssh_known_hosts:
  - $IP

before_install:
  - openssl aes-256-cbc -K $encrypted_a7dfe7f624ec_key -iv $encrypted_a7dfe7f624ec_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

# 执行部署脚本，将编译后的项目同步到服务器的webapps下
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - rsync -az --delete ./target/test-travis-ci-springboot.war root@$IP:/usr/local/project_backup/test-travis-ci-springboot.war
  - ssh -o "StrictHostKeyChecking no" -i id_rsa root@$ip "cd /usr/local/tomcat/webapps;rm -rf test-travis-ci-springboot.war;rm -rf test-travis-ci-springboot/;cp /usr/local/project_backup/test-travis-ci-springboot.war ./;exit"